name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    # Only run on Dependabot PRs
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Wait for CI to complete
      uses: fountainhead/action-wait-for-check@v1.1.0
      id: wait-for-ci
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: test
        ref: ${{ github.event.pull_request.head.sha }}
        timeoutSeconds: 1800 # 30 minutes timeout
        intervalSeconds: 30

    - name: Wait for lint to complete
      uses: fountainhead/action-wait-for-check@v1.1.0
      id: wait-for-lint
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: lint
        ref: ${{ github.event.pull_request.head.sha }}
        timeoutSeconds: 1800 # 30 minutes timeout
        intervalSeconds: 30

    - name: Get Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v1
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Auto-merge for patch and minor updates
      if: |
        steps.wait-for-ci.outputs.conclusion == 'success' &&
        steps.wait-for-lint.outputs.conclusion == 'success' &&
        (
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        )
      run: |
        echo "Auto-merging ${{ steps.metadata.outputs.dependency-names }} (${{ steps.metadata.outputs.update-type }})"
        gh pr merge --auto --squash "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Auto-merge for major updates (with manual approval)
      if: |
        steps.wait-for-ci.outputs.conclusion == 'success' &&
        steps.wait-for-lint.outputs.conclusion == 'success' &&
        steps.metadata.outputs.update-type == 'version-update:semver-major'
      run: |
        echo "Major update detected for ${{ steps.metadata.outputs.dependency-names }}"
        echo "Tests passed, but major updates require manual review."
        echo "Please review and merge manually: ${{ github.event.pull_request.html_url }}"
        gh pr comment "$PR_URL" --body "✅ Tests passed! This is a major version update that requires manual review before merging."
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Handle failed tests
      if: |
        steps.wait-for-ci.outputs.conclusion != 'success' ||
        steps.wait-for-lint.outputs.conclusion != 'success'
      run: |
        echo "Tests failed for Dependabot PR"
        echo "CI status: ${{ steps.wait-for-ci.outputs.conclusion }}"
        echo "Lint status: ${{ steps.wait-for-lint.outputs.conclusion }}"
        gh pr comment "$PR_URL" --body "❌ Tests failed. Please check the CI results before merging."
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment on successful auto-merge
      if: |
        steps.wait-for-ci.outputs.conclusion == 'success' &&
        steps.wait-for-lint.outputs.conclusion == 'success' &&
        (
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        )
      run: |
        gh pr comment "$PR_URL" --body "✅ Tests passed! Auto-merging this ${{ steps.metadata.outputs.update-type }} update for ${{ steps.metadata.outputs.dependency-names }}."
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}